### ISSUE TITLE
Feature Request: Dedupe VSS to Single File

### ISSUE THREAD

**Issue by dsplice** [EricZimmerman/MFTECmd#12]
Just querying as this would be very useful to me.  When extracting all MFT records, and including the --vss and --dedupe options, would it be possible to have the results outputted to a single file.  I am looking at seeing for complete file existence (if a file has ever existed) and would like to see if I could eliminate having to go through the MFT and each VSS file individually.  If it was possible, would love seeing it in the USNJRNL too.

**Comment by EricZimmerman** [comment]
deduped based on what? 

right now its deduping on the file itself, vs rows in the csvs.

you could cat all the files together, then do a uniq to drop dupes.

**Comment by dsplice** [comment]
I have attempted that, but due to the possibility of newlines and other
data within the CSV, a sort and uniq will not work.  I will keep seeing if
I can find another way to deduplicate the multiple files.

**Comment by dsplice** [comment]
It was a locale issue.  Please close this request.
