### ISSUE TITLE
Error: Destination location not available

### ISSUE THREAD

**Issue by devgc** [EricZimmerman/MFTECmd#2]
This should dump entry output right?

I keep getting 'Destination location not available. Verify drive letter and try again. Exiting'
```
F:\Tools\Zimmerman>MFTECmd.exe -f D:\Test\$MFT --de 5-5
MFTECmd version 0.4.2.3

Author: Eric Zimmerman (saericzimmerman@gmail.com)
https://github.com/EricZimmerman/MFTECmd

Command line: -f D:\Test\$MFT --de 5-5

File type: Mft

Destination location not available. Verify drive letter and try again. Exiting
```

**Comment by EricZimmerman** [comment]
hmm, yea, lemme check. i thnk i broke something! looking now

**Comment by EricZimmerman** [comment]
fixed.

did not bump version #, but if you update via the ps1 script it should be resolved. had wrong variable in there for a path check

please verify and close if it works out

**Comment by devgc** [comment]
Fixed. Thanks!

**Comment by EricZimmerman** [comment]
woot
