### ISSUE TITLE
Use orphaned $FILE_NAME attributes of attribute list MFT entries for path reconstruction

### ISSUE THREAD

**Issue by harelsegev** [EricZimmerman/MFTECmd#7]
See https://github.com/log2timeline/plaso/issues/3840 for more context.

**Comment by EricZimmerman** [comment]
Can you provide an actual mft where this isn't already happening? I don't see why mfte CMD wouldn't already be doing this

Mfte CMD already locates extension records and in fact is one of the only programs out there that can use extension records without a full disk image

As the program is parsing the mft it re-associates all the extension records and so it would see the file name attribute and use it regardless of what entry it was found in

So I'm afraid there's not going to be much I can do unless you have an mft that exhibits the behavior you're describing

**Comment by harelsegev** [comment]
Here you go:
[$MFT.zip](https://github.com/EricZimmerman/MFTECmd/files/7228170/MFT.zip)

The command line I used to run MFTEcmd:
* MFTECmd -f $MFT --csv . --csvf MFTECmd_output.csv

The parent path of File1.txt is unknown (.\PathUnknown\Directory with ID 0x00000026-00000001) ,but in fact it can be reconstructed using the $FILE_NAME attribute from MFT entry 43.

**Comment by EricZimmerman** [comment]
ill take a look in more detail later, but the "problem" is that the extension record cannot be associated to the base record anymore, since its been reallocated (seq #2 now, and its in use)

tomorrow i should be able to add a step to make a pass of the extension records that cannot be associated in this case to try to close this gap.

i wonder how common of an occurrence this is in the wild?

**Comment by harelsegev** [comment]
> the "problem" is that the extension record cannot be associated to the base record anymore, since its been reallocated

Yes. It's more of an idea for enhancement, rather than a "problem"

> i wonder how common of an occurrence this is in the wild?

I honestly don't know. I've seen directories with $FILE_NAME attributes in extension records before, so I guess it can happen.

**Comment by EricZimmerman** [comment]
i have this working in the mft project. will test in MFTECMD locally and then push an update

**Comment by EricZimmerman** [comment]
```
42,2,".\Folder1\File1.txt",Free,False
43,2,".\Folder1",Free,True
``

**Comment by harelsegev** [comment]
Awesome! That was fast!

**Comment by EricZimmerman** [comment]
![image](https://user-images.githubusercontent.com/4265254/134957214-40ce0361-af09-40b6-8e35-ffc96184af17.png)

wrapping up some other testing and will push new nuget and binary

**Comment by EricZimmerman** [comment]
testing other MFTs, resulted in an additional 1400+ paths being resolved. yow! They were all from the same extension record, but it worked

![image](https://user-images.githubusercontent.com/4265254/134957910-ae355152-85d8-46c7-ab8b-21d176836862.png)

**Comment by EricZimmerman** [comment]
new version is uploading here in a few.
